version: '2'
services:
  ufp-sidt-example-app:
    image: ufp-sidt-example-app:6
    restart: always
    ports:
    - "3000:3000"
    environment:
    - DEMO_SQL_HOST=todo-mysql
    - DEMO_SQL_USER=root
    - DEMO_SQL_PASSWORD=root
    - DEMO_SQL_DATABASE=sidt-todo-app


